workflows:
  my-flutter-ios-debug-workflow: # <- ID ของ Workflow (ระดับ 1)
    environment:                 # <- 'environment' เยื้อง 2 space จาก ID (ระดับ 2)
      flutter: stable
      xcode: latest
      cocoapods: 1.15.2

    # !!!!!!! ตรงนี้สำคัญ !!!!!!!
    # 'steps' ต้องเยื้อง 2 space จาก ID ของ Workflow เช่นเดียวกับ 'environment'
    steps:                       # <- 'steps' เยื้อง 2 space จาก ID (ระดับ 2)
      - name: Install Flutter dependencies
        script:
          - flutter pub get

      - name: Install iOS dependencies (CocoaPods)
        script:
          - cd ios
          - pod install --repo-update
          - cd ba
          - cd ..

      - name: Build iOS IPA (Debug)
        script:
          - flutter build ipa --debug

    artifacts:                   # <- 'artifacts' ก็ต้องเยื้อง 2 space จาก ID เช่นกัน (ระดับ 2)
      - build/ios/ipa/*.ipa

    publishing:                  # <- 'publishing' ก็ต้องเยื้อง 2 space จาก ID เช่นกัน (ระดับ 2)
      email:
        recipients:
          - your.email@example.com
        success: true
        failure: true